services:
  bot:
    container_name: pipebot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
    environment:
      - APP_ID=${APP_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - TOKEN=${TOKEN}
      - CHANNELS=${CHANNELS}
    tty: true
    restart: always
