services:
  bot:
    build: .
    container_name: pipebot
    environment:
      - APP_ID=${APP_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - TOKEN=${TOKEN}
      - CHANNELS=${CHANNELS}
    tty: true
    restart: always
